name: CI/CD Pipeline Using Github Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name : Checkout Code
          uses : actions/checkout@v4

        - name : Set up docker Buildx
          uses : docker/setup-buildx-action@v3

        - name : Log in to Docker Hub
          uses : docker/login-action@v3
          with :
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Extract git commit hash
          run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        - name: Build and Push Image
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: krishna2302/todoapp1feb:${{ env.commit_hash }}